### ISSUE TITLE
THIS IS NOT A COMPLAINT 

### ISSUE THREAD

**Issue by DupeDawn** [corndoghh/Starling-Bypass#1]
I have no idea how to actually give people praise on github and where to do it so i thought i would just open an issue and say thankyou so much for this tool. You are an absolute life saver i've been trying so hard to get starling working, there was no sources online but your tool just works straight after installing keep up the good work. :)))))

**Comment by corndoghh** [comment]
Thank you :)

I'm so glad it could help you
